/**
 * @file src/lib/db/models/Department.ts
 * @description Department Mongoose schema for company organizational structure
 * @created 2025-11-13
 * 
 * OVERVIEW:
 * Department model representing functional divisions within companies (Finance, HR,
 * Marketing, R&D). Each department has budget allocation, staff assignments, KPI tracking,
 * and unique mechanics that affect company performance. Departments enable specialized
 * operations like loan management (Finance), training programs (HR), marketing campaigns
 * (Marketing), and innovation projects (R&D).
 * 
 * SCHEMA FIELDS:
 * Core:
 * - company: Reference to Company document (required, indexed)
 * - name: Department name (Finance, HR, Marketing, R&D)
 * - type: Department type enum (finance, hr, marketing, rd)
 * - budget: Current budget allocation ($0-unlimited)
 * - budgetPercentage: Percentage of company revenue allocated (0-100%)
 * - staff: Array of Employee references assigned to department
 * - head: Department head employee reference (optional)
 * - active: Whether department is operational
 * - established: Date department was created
 * 
 * Performance Metrics (KPIs):
 * - efficiency: Operational efficiency score (0-100)
 * - performance: Overall performance rating (0-100)
 * - roi: Return on investment percentage (-100 to +500%)
 * - utilization: Resource utilization rate (0-100%)
 * - quality: Output quality score (0-100)
 * 
 * Finance Department Specific:
 * - creditScore: Company credit score (300-850, FICO-like)
 * - debtToEquity: Debt-to-equity ratio (0-10, lower is better)
 * - cashReserves: Emergency fund balance
 * - monthlyBurn: Average monthly cash burn rate
 * - runwayMonths: Months until cash depletion (calculated)
 * - activeLoans: Count of current loan obligations
 * - totalDebt: Sum of all outstanding loan balances
 * - interestExpense: Monthly interest payments
 * 
 * HR Department Specific:
 * - headcount: Total employees across all departments
 * - turnoverRate: Annual employee turnover % (0-100)
 * - avgSatisfaction: Average employee satisfaction (0-100)
 * - avgProductivity: Average employee productivity (0-100)
 * - trainingBudget: Allocated training funds
 * - trainingROI: Training return on investment (%)
 * - openPositions: Count of unfilled job postings
 * - retentionRisk: Employees at high risk of leaving
 * 
 * Marketing Department Specific:
 * - brandReputation: Public perception score (0-100)
 * - marketShare: Industry market share % (0-100)
 * - customerAcquisitionCost: Average CAC ($)
 * - lifetimeValue: Average customer LTV ($)
 * - activeCampaigns: Count of running campaigns
 * - totalReach: Total audience reached (people)
 * - conversionRate: Marketing conversion % (0-100)
 * - socialMediaFollowers: Combined social following
 * 
 * R&D Department Specific:
 * - innovationScore: Innovation capability (0-100)
 * - patentsOwned: Count of patents/IP owned
 * - activeProjects: Count of active research projects
 * - completedProjects: Lifetime completed projects
 * - technologyLevel: Tech advancement tier (1-10)
 * - researchEfficiency: Research speed multiplier (0.5-2.0x)
 * - breakthroughProbability: Chance of major discovery (0-100%)
 * 
 * Financial Tracking:
 * - totalRevenue: Lifetime revenue generated by department
 * - totalExpenses: Lifetime expenses incurred
 * - monthlyRevenue: Last 30 days revenue
 * - monthlyExpenses: Last 30 days expenses
 * - profitMargin: (revenue - expenses) / revenue * 100
 * 
 * USAGE:
 * ```typescript
 * import Department from '@/lib/db/models/Department';
 * 
 * // Create Finance department
 * const finance = await Department.create({
 *   company: companyId,
 *   name: 'Finance',
 *   type: 'finance',
 *   budget: 50000,
 *   budgetPercentage: 15,
 *   creditScore: 650,
 *   cashReserves: 100000
 * });
 * 
 * // Assign staff to department
 * await finance.updateOne({
 *   $push: { staff: employeeId },
 *   head: seniorEmployeeId
 * });
 * 
 * // Update KPIs
 * await finance.updateOne({
 *   efficiency: 82,
 *   performance: 88,
 *   roi: 125
 * });
 * 
 * // Find company's departments
 * const departments = await Department.find({ 
 *   company: companyId,
 *   active: true 
 * });
 * ```
 * 
 * IMPLEMENTATION NOTES:
 * - Budget percentage auto-updates when company revenue changes
 * - Department head must be member of staff array
 * - KPIs recalculated daily via background job
 * - ROI calculated as: (revenue - expenses) / expenses * 100
 * - Finance department tracks company-wide credit and debt
 * - HR department aggregates employee metrics across all departments
 * - Marketing department tracks brand and customer metrics
 * - R&D department manages innovation and technology advancement
 * - Cross-department synergies: R&D + Marketing, Finance + all departments
 * - Budget allocation enforced: sum of all department budgets ≤ company revenue
 * - Department dissolution requires staff reassignment or termination
 * - Virtual fields compute derived metrics without storage overhead
 */

import mongoose, { Schema, Document, Model, Types } from 'mongoose';

/**
 * Department types
 */
export type DepartmentType = 'finance' | 'hr' | 'marketing' | 'rd';

/**
 * Department names
 */
export type DepartmentName = 'Finance' | 'HR' | 'Marketing' | 'R&D';

/**
 * Department document interface
 * 
 * @interface IDepartment
 * @extends {Document}
 */
export interface IDepartment extends Document {
  // Core
  company: Types.ObjectId;
  name: DepartmentName;
  type: DepartmentType;
  budget: number;
  budgetPercentage: number;
  staff: Types.ObjectId[];
  head?: Types.ObjectId;
  active: boolean;
  established: Date;

  // Performance Metrics (KPIs)
  efficiency: number;
  performance: number;
  roi: number;
  utilization: number;
  quality: number;

  // Finance Department Specific
  creditScore?: number;
  debtToEquity?: number;
  cashReserves?: number;
  monthlyBurn?: number;
  runwayMonths?: number;
  activeLoans?: number;
  totalDebt?: number;
  interestExpense?: number;

  // HR Department Specific
  headcount?: number;
  turnoverRate?: number;
  avgSatisfaction?: number;
  avgProductivity?: number;
  trainingBudget?: number;
  trainingROI?: number;
  openPositions?: number;
  retentionRisk?: number;

  // Marketing Department Specific
  brandReputation?: number;
  marketShare?: number;
  customerAcquisitionCost?: number;
  lifetimeValue?: number;
  activeCampaigns?: number;
  totalReach?: number;
  conversionRate?: number;
  socialMediaFollowers?: number;

  // R&D Department Specific
  innovationScore?: number;
  patentsOwned?: number;
  activeProjects?: number;
  completedProjects?: number;
  technologyLevel?: number;
  researchEfficiency?: number;
  breakthroughProbability?: number;

  // Financial Tracking
  totalRevenue: number;
  totalExpenses: number;
  monthlyRevenue: number;
  monthlyExpenses: number;
  profitMargin: number;

  // Timestamps
  createdAt: Date;
  updatedAt: Date;

  // Virtual fields
  staffCount: number;
  hasHead: boolean;
  profitability: string;
  budgetHealth: string;
}

/**
 * Department schema definition
 */
const DepartmentSchema = new Schema<IDepartment>(
  {
    // Core
    company: {
      type: Schema.Types.ObjectId,
      ref: 'Company',
      required: [true, 'Company reference is required'],
      index: true,
    },
    name: {
      type: String,
      required: [true, 'Department name is required'],
      enum: {
        values: ['Finance', 'HR', 'Marketing', 'R&D'],
        message: '{VALUE} is not a valid department name',
      },
    },
    type: {
      type: String,
      required: [true, 'Department type is required'],
      enum: {
        values: ['finance', 'hr', 'marketing', 'rd'],
        message: '{VALUE} is not a valid department type',
      },
    },
    budget: {
      type: Number,
      required: true,
      default: 0,
      min: [0, 'Budget cannot be negative'],
    },
    budgetPercentage: {
      type: Number,
      required: true,
      default: 10,
      min: [0, 'Budget percentage cannot be negative'],
      max: [100, 'Budget percentage cannot exceed 100%'],
    },
    staff: {
      type: [{ type: Schema.Types.ObjectId, ref: 'Employee' }],
      default: [],
      validate: {
        validator: function (arr: Types.ObjectId[]) {
          // Limit staff to reasonable size
          return arr.length <= 1000;
        },
        message: 'Department cannot have more than 1000 staff members',
      },
    },
    head: {
      type: Schema.Types.ObjectId,
      ref: 'Employee',
      default: null,
    },
    active: {
      type: Boolean,
      required: true,
      default: true,
      index: true,
    },
    established: {
      type: Date,
      required: true,
      default: Date.now,
      immutable: true,
    },

    // Performance Metrics (KPIs)
    efficiency: {
      type: Number,
      required: true,
      default: 50,
      min: [0, 'Efficiency cannot be below 0'],
      max: [100, 'Efficiency cannot exceed 100'],
    },
    performance: {
      type: Number,
      required: true,
      default: 50,
      min: [0, 'Performance cannot be below 0'],
      max: [100, 'Performance cannot exceed 100'],
    },
    roi: {
      type: Number,
      required: true,
      default: 0,
      min: [-100, 'ROI cannot be below -100%'],
      max: [500, 'ROI cannot exceed 500%'],
    },
    utilization: {
      type: Number,
      required: true,
      default: 60,
      min: [0, 'Utilization cannot be below 0'],
      max: [100, 'Utilization cannot exceed 100'],
    },
    quality: {
      type: Number,
      required: true,
      default: 70,
      min: [0, 'Quality cannot be below 0'],
      max: [100, 'Quality cannot exceed 100'],
    },

    // Finance Department Specific
    creditScore: {
      type: Number,
      default: 650, // FICO-like starting score
      min: [300, 'Credit score cannot be below 300'],
      max: [850, 'Credit score cannot exceed 850'],
    },
    debtToEquity: {
      type: Number,
      default: 0,
      min: [0, 'Debt-to-equity ratio cannot be negative'],
      max: [10, 'Debt-to-equity ratio cannot exceed 10'],
    },
    cashReserves: {
      type: Number,
      default: 0,
      min: [0, 'Cash reserves cannot be negative'],
    },
    monthlyBurn: {
      type: Number,
      default: 0,
      min: [0, 'Monthly burn cannot be negative'],
    },
    runwayMonths: {
      type: Number,
      default: 0,
      min: [0, 'Runway cannot be negative'],
    },
    activeLoans: {
      type: Number,
      default: 0,
      min: [0, 'Active loans count cannot be negative'],
    },
    totalDebt: {
      type: Number,
      default: 0,
      min: [0, 'Total debt cannot be negative'],
    },
    interestExpense: {
      type: Number,
      default: 0,
      min: [0, 'Interest expense cannot be negative'],
    },

    // HR Department Specific
    headcount: {
      type: Number,
      default: 0,
      min: [0, 'Headcount cannot be negative'],
    },
    turnoverRate: {
      type: Number,
      default: 15, // 15% annual turnover (industry average)
      min: [0, 'Turnover rate cannot be negative'],
      max: [100, 'Turnover rate cannot exceed 100%'],
    },
    avgSatisfaction: {
      type: Number,
      default: 70,
      min: [0, 'Average satisfaction cannot be below 0'],
      max: [100, 'Average satisfaction cannot exceed 100'],
    },
    avgProductivity: {
      type: Number,
      default: 70,
      min: [0, 'Average productivity cannot be below 0'],
      max: [100, 'Average productivity cannot exceed 100'],
    },
    trainingBudget: {
      type: Number,
      default: 0,
      min: [0, 'Training budget cannot be negative'],
    },
    trainingROI: {
      type: Number,
      default: 0,
      min: [-100, 'Training ROI cannot be below -100%'],
      max: [500, 'Training ROI cannot exceed 500%'],
    },
    openPositions: {
      type: Number,
      default: 0,
      min: [0, 'Open positions cannot be negative'],
    },
    retentionRisk: {
      type: Number,
      default: 30,
      min: [0, 'Retention risk cannot be below 0'],
      max: [100, 'Retention risk cannot exceed 100'],
    },

    // Marketing Department Specific
    brandReputation: {
      type: Number,
      default: 50,
      min: [0, 'Brand reputation cannot be below 0'],
      max: [100, 'Brand reputation cannot exceed 100'],
    },
    marketShare: {
      type: Number,
      default: 0,
      min: [0, 'Market share cannot be negative'],
      max: [100, 'Market share cannot exceed 100%'],
    },
    customerAcquisitionCost: {
      type: Number,
      default: 0,
      min: [0, 'CAC cannot be negative'],
    },
    lifetimeValue: {
      type: Number,
      default: 0,
      min: [0, 'LTV cannot be negative'],
    },
    activeCampaigns: {
      type: Number,
      default: 0,
      min: [0, 'Active campaigns count cannot be negative'],
    },
    totalReach: {
      type: Number,
      default: 0,
      min: [0, 'Total reach cannot be negative'],
    },
    conversionRate: {
      type: Number,
      default: 2, // 2% baseline conversion
      min: [0, 'Conversion rate cannot be negative'],
      max: [100, 'Conversion rate cannot exceed 100%'],
    },
    socialMediaFollowers: {
      type: Number,
      default: 0,
      min: [0, 'Followers count cannot be negative'],
    },

    // R&D Department Specific
    innovationScore: {
      type: Number,
      default: 50,
      min: [0, 'Innovation score cannot be below 0'],
      max: [100, 'Innovation score cannot exceed 100'],
    },
    patentsOwned: {
      type: Number,
      default: 0,
      min: [0, 'Patents owned cannot be negative'],
    },
    activeProjects: {
      type: Number,
      default: 0,
      min: [0, 'Active projects count cannot be negative'],
    },
    completedProjects: {
      type: Number,
      default: 0,
      min: [0, 'Completed projects count cannot be negative'],
    },
    technologyLevel: {
      type: Number,
      default: 1,
      min: [1, 'Technology level must be at least 1'],
      max: [10, 'Technology level cannot exceed 10'],
    },
    researchEfficiency: {
      type: Number,
      default: 1.0,
      min: [0.5, 'Research efficiency cannot be below 0.5x'],
      max: [2.0, 'Research efficiency cannot exceed 2.0x'],
    },
    breakthroughProbability: {
      type: Number,
      default: 10, // 10% chance of breakthrough per project
      min: [0, 'Breakthrough probability cannot be negative'],
      max: [100, 'Breakthrough probability cannot exceed 100%'],
    },

    // Financial Tracking
    totalRevenue: {
      type: Number,
      required: true,
      default: 0,
      min: [0, 'Total revenue cannot be negative'],
    },
    totalExpenses: {
      type: Number,
      required: true,
      default: 0,
      min: [0, 'Total expenses cannot be negative'],
    },
    monthlyRevenue: {
      type: Number,
      required: true,
      default: 0,
      min: [0, 'Monthly revenue cannot be negative'],
    },
    monthlyExpenses: {
      type: Number,
      required: true,
      default: 0,
      min: [0, 'Monthly expenses cannot be negative'],
    },
    profitMargin: {
      type: Number,
      required: true,
      default: 0,
      min: [-100, 'Profit margin cannot be below -100%'],
      max: [100, 'Profit margin cannot exceed 100%'],
    },
  },
  {
    timestamps: true,
    collection: 'departments',
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

/**
 * Indexes for query optimization
 */
DepartmentSchema.index({ company: 1, type: 1 }, { unique: true }); // One department per type per company
DepartmentSchema.index({ company: 1, active: 1 }); // Active departments
DepartmentSchema.index({ head: 1 }); // Department heads

/**
 * Virtual field: staffCount
 */
DepartmentSchema.virtual('staffCount').get(function (this: IDepartment): number {
  return this.staff.length;
});

/**
 * Virtual field: hasHead
 */
DepartmentSchema.virtual('hasHead').get(function (this: IDepartment): boolean {
  return this.head !== null && this.head !== undefined;
});

/**
 * Virtual field: profitability
 */
DepartmentSchema.virtual('profitability').get(function (this: IDepartment): string {
  if (this.profitMargin > 20) return 'High';
  if (this.profitMargin > 0) return 'Moderate';
  if (this.profitMargin > -10) return 'Low';
  return 'Loss';
});

/**
 * Virtual field: budgetHealth
 */
DepartmentSchema.virtual('budgetHealth').get(function (this: IDepartment): string {
  const utilizationRate = this.monthlyExpenses / (this.budget / 12);
  if (utilizationRate < 0.7) return 'Underutilized';
  if (utilizationRate < 1.0) return 'Healthy';
  if (utilizationRate < 1.2) return 'Strained';
  return 'Overspent';
});

/**
 * Pre-save hook: Calculate profit margin
 */
DepartmentSchema.pre<IDepartment>('save', function (next) {
  // Calculate profit margin
  if (this.totalRevenue > 0) {
    this.profitMargin = ((this.totalRevenue - this.totalExpenses) / this.totalRevenue) * 100;
  } else {
    this.profitMargin = 0;
  }

  // Finance: Calculate runway
  if (this.type === 'finance' && this.monthlyBurn && this.monthlyBurn > 0) {
    this.runwayMonths = Math.floor((this.cashReserves || 0) / this.monthlyBurn);
  }

  next();
});

/**
 * Department model
 * 
 * @example
 * ```typescript
 * import Department from '@/lib/db/models/Department';
 * 
 * // Create department
 * const marketing = await Department.create({
 *   company: companyId,
 *   name: 'Marketing',
 *   type: 'marketing',
 *   budget: 100000,
 *   budgetPercentage: 20,
 *   brandReputation: 60,
 *   marketShare: 5
 * });
 * 
 * // Find company's departments
 * const departments = await Department.find({
 *   company: companyId,
 *   active: true
 * }).populate('staff head');
 * 
 * // Update KPIs
 * await marketing.updateOne({
 *   brandReputation: 75,
 *   activeCampaigns: 3,
 *   totalReach: 500000
 * });
 * ```
 */
const Department: Model<IDepartment> =
  mongoose.models.Department || mongoose.model<IDepartment>('Department', DepartmentSchema);

export default Department;
