/**
 * @file app/api/auth/[...nextauth]/route.ts
 * @description NextAuth.js API route handler
 * @created 2025-11-13
 * 
 * OVERVIEW:
 * NextAuth v5 catch-all API route handler.
 * Handles all authentication requests (signin, signout, callback, session).
 * Exports GET and POST handlers for Next.js App Router.
 * 
 * ROUTES:
 * - GET  /api/auth/session - Get current session
 * - POST /api/auth/signin - Sign in with credentials
 * - POST /api/auth/signout - Sign out current user
 * - GET  /api/auth/callback - OAuth callback handler
 * - GET  /api/auth/csrf - CSRF token
 * 
 * USAGE:
 * No direct usage needed - NextAuth handles all routing automatically.
 * Client-side uses signIn/signOut from next-auth/react.
 * 
 * @example
 * ```typescript
 * // Client component
 * import { signIn, signOut } from 'next-auth/react';
 * 
 * // Sign in
 * await signIn('credentials', {
 *   email: 'user@example.com',
 *   password: 'password123',
 *   redirect: true,
 *   callbackUrl: '/dashboard'
 * });
 * 
 * // Sign out
 * await signOut({ redirect: true, callbackUrl: '/' });
 * ```
 * 
 * IMPLEMENTATION NOTES:
 * - Automatically generated by NextAuth
 * - Handles CSRF protection
 * - Manages session cookies
 * - Supports multiple providers (currently credentials only)
 */

import { handlers } from '@/lib/auth/config';

/**
 * GET handler for NextAuth requests
 * 
 * @description
 * Handles GET requests for session retrieval, CSRF tokens, and callbacks.
 * 
 * @example
 * GET /api/auth/session - Returns current user session
 */
export const GET = handlers.GET;

/**
 * POST handler for NextAuth requests
 * 
 * @description
 * Handles POST requests for signin, signout, and other auth operations.
 * 
 * @example
 * POST /api/auth/signin - Authenticate user credentials
 */
export const POST = handlers.POST;
